### ISSUE TITLE
ConnectionResetError is not handled

### ISSUE THREAD

**Issue by KlipperKyle** [KlipperKyle/cpsc-471-prj3#8]
I think this ConnectionResetError is a new Python 3 thing.  The code I have for checking connection resets is not running.

```
$ ./src/server.py 2112
./src/server.py[5010]: [main] Listening on :2112
./src/server.py[5010]: [main] Awaiting connection...
./src/server.py[5010]: [main] Accepted connection from 127.0.0.1:55260
./src/server.py[5010]: [main] Forking child PID 5012
./src/server.py[5010]: [main] Awaiting connection...
./src/server.py[5012]: [handle_session] Handling connection from 127.0.0.1:55260
./src/server.py[5012]: [recv_msg] "300 LS 56789 ./"
./src/server.py[5012]: [reap_children] reaping PID 5013
./src/server.py[5012]: [send_msg] "510 540 Transfer started"
./src/server.py[5012]: [send_msg] "520 Transfer success"
./src/server.py[5012]: [recv_msg] "300 LS 49215 /"
./src/server.py[5012]: [send_msg] "390 Cannot list /"
./src/server.py[5012]: [shutdown] Shutting down...
Traceback (most recent call last):
  File "./src/server.py", line 179, in <module>
    try: main()
  File "./src/server.py", line 131, in main
    handle_session(addr)
  File "./src/server.py", line 83, in handle_session
    message = recv_msg(sock_cli)
  File "/home/kyle/git/cpsc-471-prj3/src/common.py", line 122, in recv_msg
    raw_message = read_ret(sock)
  File "/home/kyle/git/cpsc-471-prj3/src/common.py", line 47, in read_ret
    buf_tmp = sock.recv(1)
ConnectionResetError: [Errno 104] Connection reset by peer
./src/server.py[5010]: [reap_children] reaping PID 5012
```

**Comment by KlipperKyle** [comment]
On closer inspection, the code checks for disconnects.  And this issue is gone after the fix for Issue #7.

Considering that this shouldn't happen, I am going to WONTFIX this for now.
